/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mobemu.algorithms;

import mobemu.node.Context;
import mobemu.node.Message;
import mobemu.node.Node;

/**
 * Class for an Epidemic node.
 *
 * Amin Vahdat and David Becker. Epidemic Routing for Partially-Connected Ad Hoc
 * Networks. Technical report, Duke University, April 2000.
 *
 * @author Radu
 */
public class Epidemic extends Node {

    private boolean dissemination;
    private boolean altruismAnalysis;

    /**
     * Instantiates an {@code Epidemic} object.
     *
     * @param id ID of the node
     * @param nodes total number of existing nodes
     * @param context the context of this node
     * @param socialNetwork the social network as seen by this node
     * @param dataMemorySize the maximum allowed size of the data memory
     * @param exchangeHistorySize the maximum allowed size of the exchange
     * history
     * @param seed the seed for the random number generators
     * @param traceStart timestamp of the start of the trace
     * @param traceEnd timestamp of the end of the trace
     * @param dissemination {@code true} if dissemination is used, {@code false}
     * if routing is used
     * @param altruism {@code true} if altruism computations are performed,
     * {@code false} otherwise
     */
    public Epidemic(int id, int nodes, Context context, boolean[] socialNetwork, int dataMemorySize, int exchangeHistorySize,
            long seed, long traceStart, long traceEnd, boolean dissemination, boolean altruism) {
        super(id, nodes, context, socialNetwork, dataMemorySize, exchangeHistorySize, seed, traceStart, traceEnd);

        this.dissemination = dissemination;
        this.altruismAnalysis = altruism;
    }

    @Override
    public String getName() {
        return "Epidemic";
    }

    @Override
    protected void onDataExchange(Node encounteredNode, long contactDuration, long currentTime) {
        if (!(encounteredNode instanceof Epidemic)) {
            return;
        }

        Epidemic epidemicEncounteredNode = (Epidemic) encounteredNode;
        int remainingMessages = deliverDirectMessages(epidemicEncounteredNode, altruismAnalysis, contactDuration, currentTime, dissemination);
        int totalMessages = 0;

        // download each message in the encountered node's data memory that is not in the current node's memory
        for (Message message : epidemicEncounteredNode.dataMemory) {
            if (totalMessages >= remainingMessages) {
                return;
            }

            if (insertMessage(message, epidemicEncounteredNode, currentTime, altruismAnalysis, dissemination)) {
                totalMessages++;
            }

            // oldRelay.id, newRelay.id
            String messageId = "" + message.getId();
            String oldRelayId = "" + epidemicEncounteredNode.id;
            String newRelayId = "" + this.id;
            String oldFriendWithDestination = "" + (epidemicEncounteredNode.socialNetwork[message.getDestination()] ? 1 : 0);
            String newFriendWithDestination = "" + (this.socialNetwork[message.getDestination()] ? 1 : 0);
            String oldRelayBattery = "" + epidemicEncounteredNode.getBattery().getCurrentLevel();
            String newRelayBattery = "" + this.getBattery().getCurrentLevel();
            String oldRelayCentrality = "" + epidemicEncounteredNode.getCentrality(false);
            String newRelayCentrality = "" + this.getCentrality(false);
            String oldRelayLocalCentrality = "" + epidemicEncounteredNode.getCentrality(true);
            String newRelayLocalCentrality = "" + this.getCentrality(true);
            String oldCommonCommunity = "" + (epidemicEncounteredNode.inLocalCommunity(message.getDestination()) ? 1 : 0);
            String newCommonCommunity = "" + (this.inLocalCommunity(message.getDestination()) ? 1 : 0);
            String oldDataMemory = "" + epidemicEncounteredNode.dataMemorySize;
            String newDataMemory = "" + this.dataMemorySize;

            System.out.println(
                    String.join(
                            ", ",
                            oldRelayId,
                            oldFriendWithDestination,
                            oldRelayBattery,
                            oldRelayCentrality,
                            oldRelayLocalCentrality,
                            oldCommonCommunity,
                            oldDataMemory,
                            newRelayId,
                            newFriendWithDestination,
                            newRelayBattery,
                            newRelayCentrality,
                            newRelayLocalCentrality,
                            newCommonCommunity,
                            newDataMemory
                    )
            );
        }

        // download each message generated by the encountered node that is not in the current node's memory
        for (Message message : epidemicEncounteredNode.ownMessages) {
            if (totalMessages >= remainingMessages) {
                return;
            }

            if (insertMessage(message, epidemicEncounteredNode, currentTime, altruismAnalysis, dissemination)) {
                totalMessages++;
            }
        }
    }
}
